### PR TITLE
add lv2 project as sub-module and use headers from there by default

### PR DESCRIPTION
**Pull request by jjYBdx4IL**
Doesn't compile out-of-the-box because I don't have LV2 API set up. This change allows for a self-contained build while still accepting user-specified LV2 API SDK via env var.

### CODE REVIEW

**Comment by Dougal-s** [comment]
Looks good! One small thing, could you update `README.md` and the automated builds in `.github/workflows/build.yml` to use the lv2 submodule.

P.S. Sorry for taking so long to reply, I've been incredibly busy over the past while.

**Comment by jjYBdx4IL** [comment]
done

**Review by Dougal-s — CHANGES_REQUESTED** [review]
Thanks for the changes! There are just a handful of things to fix before I merge the changes.

**Comment by jjYBdx4IL** [comment]
workflow build is fine. btw: do you know if there is anything like PUGL with Metal support?

**Comment by Dougal-s** [comment]
[SDL](http://wiki.libsdl.org/FrontPage) supports metal, although it's far from minimal and does more than just manage windows. Plus, I don't think it supports embedding in native windows, which plugins UI's need to be able to do. In fact, PUGL is the only library I know of that supports embedding. You could create a window using PUGL with the stub backend and then set up metal using the native window handle. GLFW has an [example metal program](https://github.com/glfw/glfw/blob/metal-guide/examples/metal.m) that does that.

**Review by Dougal-s — APPROVED** [review]
Everything looks good!

**Pull request merged**
